//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GadgetsModel", "FK_App_Gadget", "Gadget", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SampleWeb.Models.Gadget), "App", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SampleWeb.Models.App), true)]
[assembly: EdmRelationshipAttribute("GadgetsModel", "FK_Gadget_App", "App", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SampleWeb.Models.App), "Gadget", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SampleWeb.Models.Gadget), true)]
[assembly: EdmRelationshipAttribute("GadgetsModel", "FK_Manifest_App", "App", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SampleWeb.Models.App), "Manifest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SampleWeb.Models.Manifest), true)]
[assembly: EdmRelationshipAttribute("GadgetsModel", "FK_GadgetContent_Gadget", "Gadget", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SampleWeb.Models.Gadget), "GadgetContent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SampleWeb.Models.GadgetContent), true)]
[assembly: EdmRelationshipAttribute("GadgetsModel", "FK_Manifest_Gadget", "Gadget", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SampleWeb.Models.Gadget), "Manifest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SampleWeb.Models.Manifest), true)]
[assembly: EdmRelationshipAttribute("GadgetsModel", "FK_GadgetContent_RecordType", "RecordType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SampleWeb.Models.RecordType), "GadgetContent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SampleWeb.Models.GadgetContent), true)]

#endregion

namespace SampleWeb.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GadgetsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GadgetsEntities object using the connection string found in the 'GadgetsEntities' section of the application configuration file.
        /// </summary>
        public GadgetsEntities() : base("name=GadgetsEntities", "GadgetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GadgetsEntities object.
        /// </summary>
        public GadgetsEntities(string connectionString) : base(connectionString, "GadgetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GadgetsEntities object.
        /// </summary>
        public GadgetsEntities(EntityConnection connection) : base(connection, "GadgetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<App> Apps
        {
            get
            {
                if ((_Apps == null))
                {
                    _Apps = base.CreateObjectSet<App>("Apps");
                }
                return _Apps;
            }
        }
        private ObjectSet<App> _Apps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Gadget> Gadgets
        {
            get
            {
                if ((_Gadgets == null))
                {
                    _Gadgets = base.CreateObjectSet<Gadget>("Gadgets");
                }
                return _Gadgets;
            }
        }
        private ObjectSet<Gadget> _Gadgets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GadgetContent> GadgetContents
        {
            get
            {
                if ((_GadgetContents == null))
                {
                    _GadgetContents = base.CreateObjectSet<GadgetContent>("GadgetContents");
                }
                return _GadgetContents;
            }
        }
        private ObjectSet<GadgetContent> _GadgetContents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Manifest> Manifests
        {
            get
            {
                if ((_Manifests == null))
                {
                    _Manifests = base.CreateObjectSet<Manifest>("Manifests");
                }
                return _Manifests;
            }
        }
        private ObjectSet<Manifest> _Manifests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecordType> RecordTypes
        {
            get
            {
                if ((_RecordTypes == null))
                {
                    _RecordTypes = base.CreateObjectSet<RecordType>("RecordTypes");
                }
                return _RecordTypes;
            }
        }
        private ObjectSet<RecordType> _RecordTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Apps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApps(App app)
        {
            base.AddObject("Apps", app);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Gadgets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGadgets(Gadget gadget)
        {
            base.AddObject("Gadgets", gadget);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GadgetContents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGadgetContents(GadgetContent gadgetContent)
        {
            base.AddObject("GadgetContents", gadgetContent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Manifests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToManifests(Manifest manifest)
        {
            base.AddObject("Manifests", manifest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecordTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecordTypes(RecordType recordType)
        {
            base.AddObject("RecordTypes", recordType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GadgetsModel", Name="App")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class App : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new App object.
        /// </summary>
        /// <param name="appId">Initial value of the AppId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="updateDate">Initial value of the UpdateDate property.</param>
        public static App CreateApp(global::System.Int32 appId, global::System.String name, global::System.DateTime createDate, global::System.DateTime updateDate)
        {
            App app = new App();
            app.AppId = appId;
            app.Name = name;
            app.CreateDate = createDate;
            app.UpdateDate = updateDate;
            return app;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppId
        {
            get
            {
                return _AppId;
            }
            set
            {
                if (_AppId != value)
                {
                    OnAppIdChanging(value);
                    ReportPropertyChanging("AppId");
                    _AppId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppId");
                    OnAppIdChanged();
                }
            }
        }
        private global::System.Int32 _AppId;
        partial void OnAppIdChanging(global::System.Int32 value);
        partial void OnAppIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SourceUrl
        {
            get
            {
                return _SourceUrl;
            }
            set
            {
                OnSourceUrlChanging(value);
                ReportPropertyChanging("SourceUrl");
                _SourceUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SourceUrl");
                OnSourceUrlChanged();
            }
        }
        private global::System.String _SourceUrl;
        partial void OnSourceUrlChanging(global::System.String value);
        partial void OnSourceUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ManifestUrl
        {
            get
            {
                return _ManifestUrl;
            }
            set
            {
                OnManifestUrlChanging(value);
                ReportPropertyChanging("ManifestUrl");
                _ManifestUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ManifestUrl");
                OnManifestUrlChanged();
            }
        }
        private global::System.String _ManifestUrl;
        partial void OnManifestUrlChanging(global::System.String value);
        partial void OnManifestUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LatestGadgetID
        {
            get
            {
                return _LatestGadgetID;
            }
            set
            {
                OnLatestGadgetIDChanging(value);
                ReportPropertyChanging("LatestGadgetID");
                _LatestGadgetID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LatestGadgetID");
                OnLatestGadgetIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LatestGadgetID;
        partial void OnLatestGadgetIDChanging(Nullable<global::System.Int32> value);
        partial void OnLatestGadgetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private global::System.DateTime _UpdateDate;
        partial void OnUpdateDateChanging(global::System.DateTime value);
        partial void OnUpdateDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_App_Gadget", "Gadget")]
        public Gadget Gadget
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_App_Gadget", "Gadget").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_App_Gadget", "Gadget").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Gadget> GadgetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_App_Gadget", "Gadget");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Gadget>("GadgetsModel.FK_App_Gadget", "Gadget", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_Gadget_App", "Gadget")]
        public EntityCollection<Gadget> Gadgets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Gadget>("GadgetsModel.FK_Gadget_App", "Gadget");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Gadget>("GadgetsModel.FK_Gadget_App", "Gadget", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_Manifest_App", "Manifest")]
        public EntityCollection<Manifest> Manifests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Manifest>("GadgetsModel.FK_Manifest_App", "Manifest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Manifest>("GadgetsModel.FK_Manifest_App", "Manifest", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GadgetsModel", Name="Gadget")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gadget : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Gadget object.
        /// </summary>
        /// <param name="gadgetID">Initial value of the GadgetID property.</param>
        /// <param name="isLatest">Initial value of the IsLatest property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="updateDate">Initial value of the UpdateDate property.</param>
        public static Gadget CreateGadget(global::System.Int32 gadgetID, global::System.Boolean isLatest, global::System.DateTime createDate, global::System.DateTime updateDate)
        {
            Gadget gadget = new Gadget();
            gadget.GadgetID = gadgetID;
            gadget.IsLatest = isLatest;
            gadget.CreateDate = createDate;
            gadget.UpdateDate = updateDate;
            return gadget;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GadgetID
        {
            get
            {
                return _GadgetID;
            }
            set
            {
                if (_GadgetID != value)
                {
                    OnGadgetIDChanging(value);
                    ReportPropertyChanging("GadgetID");
                    _GadgetID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GadgetID");
                    OnGadgetIDChanged();
                }
            }
        }
        private global::System.Int32 _GadgetID;
        partial void OnGadgetIDChanging(global::System.Int32 value);
        partial void OnGadgetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppID
        {
            get
            {
                return _AppID;
            }
            set
            {
                OnAppIDChanging(value);
                ReportPropertyChanging("AppID");
                _AppID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppID");
                OnAppIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AppID;
        partial void OnAppIDChanging(Nullable<global::System.Int32> value);
        partial void OnAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TitleUrl
        {
            get
            {
                return _TitleUrl;
            }
            set
            {
                OnTitleUrlChanging(value);
                ReportPropertyChanging("TitleUrl");
                _TitleUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TitleUrl");
                OnTitleUrlChanged();
            }
        }
        private global::System.String _TitleUrl;
        partial void OnTitleUrlChanging(global::System.String value);
        partial void OnTitleUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SourceUrl
        {
            get
            {
                return _SourceUrl;
            }
            set
            {
                OnSourceUrlChanging(value);
                ReportPropertyChanging("SourceUrl");
                _SourceUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SourceUrl");
                OnSourceUrlChanged();
            }
        }
        private global::System.String _SourceUrl;
        partial void OnSourceUrlChanging(global::System.String value);
        partial void OnSourceUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsLatest
        {
            get
            {
                return _IsLatest;
            }
            set
            {
                OnIsLatestChanging(value);
                ReportPropertyChanging("IsLatest");
                _IsLatest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsLatest");
                OnIsLatestChanged();
            }
        }
        private global::System.Boolean _IsLatest;
        partial void OnIsLatestChanging(global::System.Boolean value);
        partial void OnIsLatestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private global::System.DateTime _UpdateDate;
        partial void OnUpdateDateChanging(global::System.DateTime value);
        partial void OnUpdateDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_App_Gadget", "App")]
        public EntityCollection<App> Apps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<App>("GadgetsModel.FK_App_Gadget", "App");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<App>("GadgetsModel.FK_App_Gadget", "App", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_Gadget_App", "App")]
        public App App
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<App>("GadgetsModel.FK_Gadget_App", "App").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<App>("GadgetsModel.FK_Gadget_App", "App").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<App> AppReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<App>("GadgetsModel.FK_Gadget_App", "App");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<App>("GadgetsModel.FK_Gadget_App", "App", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_GadgetContent_Gadget", "GadgetContent")]
        public EntityCollection<GadgetContent> GadgetContents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GadgetContent>("GadgetsModel.FK_GadgetContent_Gadget", "GadgetContent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GadgetContent>("GadgetsModel.FK_GadgetContent_Gadget", "GadgetContent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_Manifest_Gadget", "Manifest")]
        public EntityCollection<Manifest> Manifests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Manifest>("GadgetsModel.FK_Manifest_Gadget", "Manifest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Manifest>("GadgetsModel.FK_Manifest_Gadget", "Manifest", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GadgetsModel", Name="GadgetContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GadgetContent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GadgetContent object.
        /// </summary>
        /// <param name="gadgetContentID">Initial value of the GadgetContentID property.</param>
        /// <param name="gadgetID">Initial value of the GadgetID property.</param>
        /// <param name="recordTypeID">Initial value of the RecordTypeID property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="updateDate">Initial value of the UpdateDate property.</param>
        public static GadgetContent CreateGadgetContent(global::System.Int32 gadgetContentID, global::System.Int32 gadgetID, global::System.Int32 recordTypeID, global::System.DateTime createDate, global::System.DateTime updateDate)
        {
            GadgetContent gadgetContent = new GadgetContent();
            gadgetContent.GadgetContentID = gadgetContentID;
            gadgetContent.GadgetID = gadgetID;
            gadgetContent.RecordTypeID = recordTypeID;
            gadgetContent.CreateDate = createDate;
            gadgetContent.UpdateDate = updateDate;
            return gadgetContent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GadgetContentID
        {
            get
            {
                return _GadgetContentID;
            }
            set
            {
                if (_GadgetContentID != value)
                {
                    OnGadgetContentIDChanging(value);
                    ReportPropertyChanging("GadgetContentID");
                    _GadgetContentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GadgetContentID");
                    OnGadgetContentIDChanged();
                }
            }
        }
        private global::System.Int32 _GadgetContentID;
        partial void OnGadgetContentIDChanging(global::System.Int32 value);
        partial void OnGadgetContentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GadgetID
        {
            get
            {
                return _GadgetID;
            }
            set
            {
                OnGadgetIDChanging(value);
                ReportPropertyChanging("GadgetID");
                _GadgetID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GadgetID");
                OnGadgetIDChanged();
            }
        }
        private global::System.Int32 _GadgetID;
        partial void OnGadgetIDChanging(global::System.Int32 value);
        partial void OnGadgetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecordTypeID
        {
            get
            {
                return _RecordTypeID;
            }
            set
            {
                OnRecordTypeIDChanging(value);
                ReportPropertyChanging("RecordTypeID");
                _RecordTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordTypeID");
                OnRecordTypeIDChanged();
            }
        }
        private global::System.Int32 _RecordTypeID;
        partial void OnRecordTypeIDChanging(global::System.Int32 value);
        partial void OnRecordTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private global::System.DateTime _UpdateDate;
        partial void OnUpdateDateChanging(global::System.DateTime value);
        partial void OnUpdateDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_GadgetContent_Gadget", "Gadget")]
        public Gadget Gadget
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_GadgetContent_Gadget", "Gadget").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_GadgetContent_Gadget", "Gadget").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Gadget> GadgetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_GadgetContent_Gadget", "Gadget");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Gadget>("GadgetsModel.FK_GadgetContent_Gadget", "Gadget", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_GadgetContent_RecordType", "RecordType")]
        public RecordType RecordType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecordType>("GadgetsModel.FK_GadgetContent_RecordType", "RecordType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecordType>("GadgetsModel.FK_GadgetContent_RecordType", "RecordType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RecordType> RecordTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecordType>("GadgetsModel.FK_GadgetContent_RecordType", "RecordType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RecordType>("GadgetsModel.FK_GadgetContent_RecordType", "RecordType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GadgetsModel", Name="Manifest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Manifest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Manifest object.
        /// </summary>
        /// <param name="appID">Initial value of the AppID property.</param>
        /// <param name="gadgetID">Initial value of the GadgetID property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static Manifest CreateManifest(global::System.Int32 appID, global::System.Int32 gadgetID, global::System.DateTime createDate)
        {
            Manifest manifest = new Manifest();
            manifest.AppID = appID;
            manifest.GadgetID = gadgetID;
            manifest.CreateDate = createDate;
            return manifest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppID
        {
            get
            {
                return _AppID;
            }
            set
            {
                if (_AppID != value)
                {
                    OnAppIDChanging(value);
                    ReportPropertyChanging("AppID");
                    _AppID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppID");
                    OnAppIDChanged();
                }
            }
        }
        private global::System.Int32 _AppID;
        partial void OnAppIDChanging(global::System.Int32 value);
        partial void OnAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GadgetID
        {
            get
            {
                return _GadgetID;
            }
            set
            {
                if (_GadgetID != value)
                {
                    OnGadgetIDChanging(value);
                    ReportPropertyChanging("GadgetID");
                    _GadgetID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GadgetID");
                    OnGadgetIDChanged();
                }
            }
        }
        private global::System.Int32 _GadgetID;
        partial void OnGadgetIDChanging(global::System.Int32 value);
        partial void OnGadgetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_Manifest_App", "App")]
        public App App
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<App>("GadgetsModel.FK_Manifest_App", "App").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<App>("GadgetsModel.FK_Manifest_App", "App").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<App> AppReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<App>("GadgetsModel.FK_Manifest_App", "App");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<App>("GadgetsModel.FK_Manifest_App", "App", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_Manifest_Gadget", "Gadget")]
        public Gadget Gadget
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_Manifest_Gadget", "Gadget").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_Manifest_Gadget", "Gadget").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Gadget> GadgetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gadget>("GadgetsModel.FK_Manifest_Gadget", "Gadget");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Gadget>("GadgetsModel.FK_Manifest_Gadget", "Gadget", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GadgetsModel", Name="RecordType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecordType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecordType object.
        /// </summary>
        /// <param name="recordTypeID">Initial value of the RecordTypeID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static RecordType CreateRecordType(global::System.Int32 recordTypeID, global::System.String name)
        {
            RecordType recordType = new RecordType();
            recordType.RecordTypeID = recordTypeID;
            recordType.Name = name;
            return recordType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecordTypeID
        {
            get
            {
                return _RecordTypeID;
            }
            set
            {
                if (_RecordTypeID != value)
                {
                    OnRecordTypeIDChanging(value);
                    ReportPropertyChanging("RecordTypeID");
                    _RecordTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecordTypeID");
                    OnRecordTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _RecordTypeID;
        partial void OnRecordTypeIDChanging(global::System.Int32 value);
        partial void OnRecordTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GadgetsModel", "FK_GadgetContent_RecordType", "GadgetContent")]
        public EntityCollection<GadgetContent> GadgetContents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GadgetContent>("GadgetsModel.FK_GadgetContent_RecordType", "GadgetContent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GadgetContent>("GadgetsModel.FK_GadgetContent_RecordType", "GadgetContent", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
