//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoSql {
    
    
    public partial class _Default {
        
        /// <summary>
        /// gadgetGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Negroni.RenderInlineControl gadgetGrid;
        
        /// <summary>
        /// RenderInlineControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Negroni.RenderInlineControl RenderInlineControl1;
        
        /// <summary>
        /// RenderInlineControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Negroni.RenderInlineControl RenderInlineControl2;
    }
}
